<a href="https://colab.research.google.com/github/edufs29/Faculdade-CalculoNumerico/blob/main/Ex4_Atividade_Pratica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Ajuste de curva com regressão quadratica

from numpy import matrix, linalg
import numpy as np

#Definindo a função
print('Função definida: ')
print('a0 + a1*x + a2*(x**2)')

# Número de pontos
m = 3

#Coordenadas
x0 = 1
y0 = 233
x1 = 6
y1 = 101
x2 = 12
y2 = 168


#Realiza os somatórios

somaX0 = (x0 + x1 + x2)
somaX1 = (x0**2) + (x1**2) + (x2**2)
somaX2 = (x0**3) + (x1**3) + (x2**3)
somaX3 = (x0**4) + (x1**4) + (x2**4)

somaY1 = (y0 + y1 + y2)
somaY2 = (x0 * y0) + (x1 * y1) + (x2 * y2)
somaY3 = ((x0**2)*y0) + ((x1**2)*y1) + ((x2**2)*y2)

#Monta as mantrizes
matrizA = np.array([[m, somaX0, somaX1], [somaX0, somaX1, somaX2], [somaX1, somaX2, somaX3]])
matrizB = np.array([[somaY1], [somaY2], [somaY3]])
print('Matriz A')
print(matrizA)
print('Matriz B')
print(matrizB)

#Metodo de Cramer
matrizA0 = np.array([[matrizB[0, 0], matrizA[0, 1], matrizA[0,2]], 
                     [matrizB[1,0], matrizA[1,1], matrizA[1,2]],
                     [matrizB[2,0], matrizA[2,1], matrizA[2,2]]])
matrizA1 = np.array([[matrizA[0, 0], matrizB[0, 0], matrizA[0,2]], 
                     [matrizA[1,0], matrizB[1,0], matrizA[1,2]],
                     [matrizA[2,0], matrizB[2,0], matrizA[2,2]]])
matrizA2 = np.array([[matrizA[0, 0], matrizA[0, 1], matrizB[0,0]], 
                     [matrizA[1,0], matrizA[1,1], matrizB[1,0]],
                     [matrizA[2,0], matrizA[2,1], matrizB[2,0]]])

#Calculo dos determinantes

det_a = linalg.det(matrizA)
det_a0 = linalg.det(matrizA0)
det_a1 = linalg.det(matrizA1)
det_a2 = linalg.det(matrizA2)

print('Matriz A0')
print(matrizA0)
print('Determinante: ' + str(det_a0))
print('Matriz A1')
print(matrizA1)
print('Determinante: ' + str(det_a1))                    
print('Matriz A2')
print(matrizA2)
print('Determinante: ' + str(det_a2))

a0 = round(det_a0 / det_a, 6)
a1 = round(det_a1 / det_a, 6)
a2 = round(det_a2 / det_a, 6)

matriz_S = np.array([[a0], [a1], [a2]])

print('A solução encontrada para o metodo foi a matriz: ')
print(matriz_S)
print('Determinante de A: ' + str(det_a))

print('A função é: '+ str(a0) + ' + ' + str(a1) + ' * x + ' + str(a2) + ' * xˆ2')

#Calculo da solução para o valor de x apresentado

x = 2
y = a0 + (a1 * x) + (a2 * (x**2))

print('Para x = ' + str(x) + ' o y = '+ str(y))


#Calculo do residuo

y0i = a0 + (a1 * x0) + (a2 * (x0**2))
y1i = a0 + (a1 * x1) + (a2 * (x1**2))
y2i = a0 + (a1 * x2) + (a2 * (x2**2))

R = ((y0 - y0i)**2) + ((y1-y1i)**2) + ((y2 - y2i)**2)
print('O residuo para a função é: ' + str(R))


Função definida: 
a0 + a1*x + a2*(x**2)
Matriz A
[[    3    19   181]
 [   19   181  1945]
 [  181  1945 22033]]
Matriz B
[[  502]
 [ 2855]
 [28061]]
Matriz A0
[[  502    19   181]
 [ 2855   181  1945]
 [28061  1945 22033]]
Determinante: 30480119.999999937
Matriz A1
[[    3   502   181]
 [   19  2855  1945]
 [  181 28061 22033]]
Determinante: -5478329.999999996
Matriz A2
[[    3    19   502]
 [   19   181  2855]
 [  181  1945 28061]]
Determinante: 371909.9999999997
A solução encontrada para o metodo foi a matriz: 
[[279.890909]
 [-50.306061]
 [  3.415152]]
Determinante de A: 108900.00000000092
A função é: 279.890909 + -50.306061 * x + 3.415152 * xˆ2
Para x = 2 o y = 192.93939500000002
O residuo para a função é: 4.450000001403896e-09
