<a href="https://colab.research.google.com/github/edufs29/Faculdade-CalculoNumerico/blob/main/Interpolacao_Reducao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
# Ajuste de curva com regressão quadratica

from numpy import matrix, linalg
import numpy as np

#Definindo a função
print('Função definida: ')
print('a0 + a1*x + a2*(x**2)')

# Número de pontos
m = 3

#Coordenadas
x0 = 0
y0 = 0
x1 = 5
y1 = 2.846954
x2 = 10
y2 = 1.795416


#Realiza os somatórios

somaX0 = (x0 + x1 + x2)
somaX1 = (x0**2) + (x1**2) + (x2**2)
somaX2 = (x0**3) + (x1**3) + (x2**3)
somaX3 = (x0**4) + (x1**4) + (x2**4)

somaY1 = (y0 + y1 + y2)
somaY2 = (x0 * y0) + (x1 * y1) + (x2 * y2)
somaY3 = ((x0**2)*y0) + ((x1**2)*y1) + ((x2**2)*y2)

#Monta as mantrizes
matrizA = np.array([[m, somaX0, somaX1], [somaX0, somaX1, somaX2], [somaX1, somaX2, somaX3]])
matrizB = np.array([[somaY1], [somaY2], [somaY3]])
print('Matriz A')
print(matrizA)
print('Matriz B')
print(matrizB)

#Metodo de Cramer
matrizA0 = np.array([[matrizB[0, 0], matrizA[0, 1], matrizA[0,2]], 
                     [matrizB[1,0], matrizA[1,1], matrizA[1,2]],
                     [matrizB[2,0], matrizA[2,1], matrizA[2,2]]])
matrizA1 = np.array([[matrizA[0, 0], matrizB[0, 0], matrizA[0,2]], 
                     [matrizA[1,0], matrizB[1,0], matrizA[1,2]],
                     [matrizA[2,0], matrizB[2,0], matrizA[2,2]]])
matrizA2 = np.array([[matrizA[0, 0], matrizA[0, 1], matrizB[0,0]], 
                     [matrizA[1,0], matrizA[1,1], matrizB[1,0]],
                     [matrizA[2,0], matrizA[2,1], matrizB[2,0]]])

#Calculo dos determinantes

det_a = linalg.det(matrizA)
det_a0 = linalg.det(matrizA0)
det_a1 = linalg.det(matrizA1)
det_a2 = linalg.det(matrizA2)

print('Matriz A0')
print(matrizA0)
print('Determinante: ' + str(det_a0))
print('Matriz A1')
print(matrizA1)
print('Determinante: ' + str(det_a1))                    
print('Matriz A2')
print(matrizA2)
print('Determinante: ' + str(det_a2))

a0 = det_a0 / det_a
a1 = det_a1 / det_a
a2 = det_a2 / det_a

matriz_S = np.array([[a0], [a1], [a2]])

print('A solução encontrada para o metodo foi a matriz: ')
print(matriz_S)
print('Determinante de A: ' + str(det_a))

print('A função é: '+ str(a0) + ' + ' + str(a1) + ' * x + ' + str(a2) + ' * xˆ2')

#Calculo da solução para o valor de x apresentado

x = 1
y = a0 + (a1 * x) + (a2 * (x**2))

print('Para x = ' + str(x) + ' o y = '+ str(y))


#Calculo do residuo

y0i = a0 + (a1 * x0) + (a2 * (x0**2))
y1i = a0 + (a1 * x1) + (a2 * (x1**2))
y2i = a0 + (a1 * x2) + (a2 * (x2**2))

R = ((y0 - y0i)**2) + ((y1-y1i)**2) + ((y2 - y2i)**2)
print('O residuo para a função é: ' + str(R))


Função definida: 
a0 + a1*x + a2*(x**2)
Matriz A
[[    3    15   125]
 [   15   125  1125]
 [  125  1125 10625]]
Matriz B
[[  4.64237]
 [ 32.18893]
 [250.71545]]
Matriz A0
[[4.6423700e+00 1.5000000e+01 1.2500000e+02]
 [3.2188930e+01 1.2500000e+02 1.1250000e+03]
 [2.5071545e+02 1.1250000e+03 1.0625000e+04]]
Determinante: -2.0775338782641522e-10
Matriz A1
[[3.0000000e+00 4.6423700e+00 1.2500000e+02]
 [1.5000000e+01 3.2188930e+01 1.1250000e+03]
 [1.2500000e+02 2.5071545e+02 1.0625000e+04]]
Determinante: 59952.50000000006
Matriz A2
[[   3.        15.         4.64237]
 [  15.       125.        32.18893]
 [ 125.      1125.       250.71545]]
Determinante: -4873.115000000005
A solução encontrada para o metodo foi a matriz: 
[[-3.32405421e-15]
 [ 9.59240000e-01]
 [-7.79698400e-02]]
Determinante de A: 62500.00000000017
A função é: -3.3240542052226344e-15 + 0.9592399999999983 * x + -0.07796983999999987 * xˆ2
Para x = 1 o y = 0.8812701599999951
O residuo para a função é: 1.4693062728357757e-28
