<a href="https://colab.research.google.com/github/edufs29/Faculdade-CalculoNumerico/blob/main/Metodo_Newton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# coding=utf-8
# This is a sample Python script.

import numpy as np

# Criando as matrizes

# Definição da matriz jacobiana

# Parametros iniciais
from numpy import linalg

x1 = 0.0
x2 = 0.0


# termos da matriz jacobiana
error1 = 1
error2 = 1


while error1 >= 0.01 and error2 >= 0.01:

    j11 = 6 * x1
    j12 = 5
    j21 = 2
    j22 = 3 * (x2 ** 3)

    matrix_J = np.array([[j11, j12], [j21, j22]])

    f1 = 3 * (x1 ** 2) + (5 * x2) - 13
    f2 = (2 * x1) + (x2 ** 3) - 6

    matrix_F = np.array([[f1], [f2]])

    matrix_A = np.array([[j11, j12], [j21, j22]])
    matrix_B = np.array([[-f1], [-f2]])
    print('Matriz A:')
    print(matrix_A)
    print('Matriz B:')
    print(matrix_B)

    det_mat_A = linalg.det(matrix_A)

    if det_mat_A == 0:
        print('Esse sistema não pode ser resolvido por Cramer')
    else:
        print('O determinante da matriz A não é nulo: ')
        print(det_mat_A)

    # Buscando elementos da matriz B
    b1 = matrix_B[0, 0]
    b2 = matrix_B[1, 0]

    # Buscando elementos da matriz A
    a11 = matrix_A[0, 0]
    a21 = matrix_A[0, 1]
    a12 = matrix_A[1, 0]
    a22 = matrix_A[1, 1]

    # Redefinindo as matrizes A1 e A2
    matrix_A1 = np.array([[b1, a21], [b2, a22]])
    print('Matriz A1')
    print(matrix_A1)
    matrix_A2 = np.array([[a11, b1], [a12, b2]])
    print('Matriz A2')
    print(matrix_A2)

    # Calculando os determinantes

    det_mat_A1 = linalg.det(matrix_A1)
    print('Matriz A1')
    print(matrix_A1)
    print('Determinate A1')
    print(det_mat_A1)

    det_mat_A2 = linalg.det(matrix_A2)
    print('Matriz A2')
    print(matrix_A2)
    print('Determinante A2')
    print(det_mat_A2)

    # Calculando a matriz Solução
    matrix_S = np.array([[det_mat_A1 / det_mat_A], [det_mat_A2 / det_mat_A]])

    S1 = matrix_S[0, 0]
    S2 = matrix_S[1, 0]

    if x1 == 0:
        error1 = (S1 - x1)
    else:
        error1 = (S1 - x1)/x1
    if x2 == 0:
        error2 = (S2 - x2)
    else:
        error2 = (S2 - x2)/x2

    x1 = round(x1 + S1, 6)
    x2 = round(x2 + S2, 6)
else:
    print(' A Matriz solução:')
    matrix_S = np.array([[x1], [x2]])
    print(matrix_S)


Matriz A:
[[0. 5.]
 [2. 0.]]
Matriz B:
[[13.]
 [ 6.]]
O determinante da matriz A não é nulo: 
-9.999999999999998
Matriz A1
[[13.  5.]
 [ 6.  0.]]
Matriz A2
[[ 0. 13.]
 [ 2.  6.]]
Matriz A1
[[13.  5.]
 [ 6.  0.]]
Determinate A1
-30.000000000000004
Matriz A2
[[ 0. 13.]
 [ 2.  6.]]
Determinante A2
-26.000000000000004
Matriz A:
[[18.     5.   ]
 [ 2.    52.728]]
Matriz B:
[[-27.   ]
 [-17.576]]
O determinante da matriz A não é nulo: 
939.1040000000005
Matriz A1
[[-27.      5.   ]
 [-17.576  52.728]]
Matriz A2
[[ 18.    -27.   ]
 [  2.    -17.576]]
Matriz A1
[[-27.      5.   ]
 [-17.576  52.728]]
Determinate A1
-1335.776
Matriz A2
[[ 18.    -27.   ]
 [  2.    -17.576]]
Determinante A2
-262.3679999999998
 A Matriz solução:
[[1.577606]
 [2.320619]]
