<a href="https://colab.research.google.com/github/edufs29/Faculdade-CalculoNumerico/blob/main/Metodo_Cramer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# coding=utf-8
# This is a sample Python script.

import numpy as np

# Criando as matrizes
from numpy.linalg import linalg

# Criando as matrizes
print ('A*X=B')


matrix_A = np.array([[5.0, -2.0, 1.0], [1.0, 2.0, -1.0], [-1.0, -1.0, 3.0]])
matrix_B = np.array([[9.0], [-3.0], [6.0]])

print('Matriz A:')
print(matrix_A)
print('Matriz B:')
print(matrix_B)

# Determinante da matriz A

det_mat_A = linalg.det(matrix_A)

if det_mat_A == 0:
    print('Esse sistema não pode ser resolvido por Cramer')
else:
    print('O determinante da matriz A não é nulo: ')
    print(det_mat_A)

# Buscando elementos da matriz B
b1 = matrix_B[0, 0]
b2 = matrix_B[1, 0]
b3 = matrix_B[2, 0]

# Buscando elementos da matriz A
a11 = matrix_A[0, 0]
a21 = matrix_A[0, 1]
a31 = matrix_A[0, 2]
a12 = matrix_A[1, 0]
a22 = matrix_A[1, 1]
a32 = matrix_A[1, 2]
a13 = matrix_A[2, 0]
a23 = matrix_A[2, 1]
a33 = matrix_A[2, 2]

# Redefinindo as matrizes A1, A2 e A3
matrix_A1 = np.array([[b1, a21, a31], [b2, a22, a32], [b3, a23, a33]])
print('Matriz A1')
print(matrix_A1)
matrix_A2 = np.array([[a11, b1, a31], [a12, b2, a32], [a13, b3, a33]])
print('Matriz A2')
print(matrix_A2)
matrix_A3 = np.array([[a11, a21, b1], [a12, a22, b2], [a13, a23, b3]])
print('Matriz A3')
print(matrix_A3)

# Calculando os determinantes

det_mat_A1 = linalg.det(matrix_A1)
print('Matriz A1')
print(matrix_A1)
print('Determinate A1')
print(det_mat_A1)

det_mat_A2 = linalg.det(matrix_A2)
print('Matriz A2')
print(matrix_A2)
print('Determinante A2')
print(det_mat_A2)

det_mat_A3 = linalg.det(matrix_A3)
print('Matriz A3')
print(matrix_A3)
print('Determiante A3')
print(det_mat_A3)

# Calculando a matriz Solução
matrix_S = np.array([[det_mat_A1/det_mat_A], [det_mat_A2/det_mat_A], [det_mat_A3/det_mat_A]])
print('Matriz solução')
print(matrix_S)


A*X=B
Matriz A:
[[ 5. -2.  1.]
 [ 1.  2. -1.]
 [-1. -1.  3.]]
Matriz B:
[[ 9.]
 [-3.]
 [ 6.]]
O determinante da matriz A não é nulo: 
29.99999999999999
Matriz A1
[[ 9. -2.  1.]
 [-3.  2. -1.]
 [ 6. -1.  3.]]
Matriz A2
[[ 5.  9.  1.]
 [ 1. -3. -1.]
 [-1.  6.  3.]]
Matriz A3
[[ 5. -2.  9.]
 [ 1.  2. -3.]
 [-1. -1.  6.]]
Matriz A1
[[ 9. -2.  1.]
 [-3.  2. -1.]
 [ 6. -1.  3.]]
Determinate A1
30.000000000000014
Matriz A2
[[ 5.  9.  1.]
 [ 1. -3. -1.]
 [-1.  6.  3.]]
Determinante A2
-30.000000000000004
Matriz A3
[[ 5. -2.  9.]
 [ 1.  2. -3.]
 [-1. -1.  6.]]
Determiante A3
59.999999999999986
Matriz solução
[[ 1.]
 [-1.]
 [ 2.]]
